<?php

namespace opheugene\LibraryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
	public function findAllOrderedByReadDate()
    {
    	$em = $this->getEntityManager();
        
        $query = $em->createQueryBuilder('b')
        		->select('b')
        		->from('opheugeneLibraryBundle:Book', 'b')
				->orderBy('b.read', 'ASC')
				->getQuery();
		
		return $query->useResultCache(true, 360, 'book_list')->getResult();
    }
}
