index:
    path:     /
    defaults: { _controller: OpheugeneLibraryBundle:Default:index }

new:
    path:     /new
    defaults: { _controller: OpheugeneLibraryBundle:Default:new }

update:
    path:     /book/{id}
    defaults: { _controller: OpheugeneLibraryBundle:Default:update }
    
hello:
    path:     /hello/{name}
    defaults: { _controller: OpheugeneLibraryBundle:Default:hello }
