parameters:
#    opheugene_library.example.class: opheugene\LibraryBundle\Example

#services:
#    opheugene_library.example:
#        class: %opheugene_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    opheugene.twig.opheugene_extension:
        class: opheugene\LibraryBundle\Twig\opheugeneExtension
        tags:
            - { name: twig.extension }
    my.subscriber:
        class: opheugene\LibraryBundle\EventListener\DeleteBookSubscriber
        tags:
            - { name: doctrine.event_subscriber }
